<?php
/**
 * DebtorCompanyOnOrderCreatedResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billie Paella
 *
 * API Specification for Paella API
 *
 * OpenAPI spec version: 1.0
 * Contact: engineering@billie.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * DebtorCompanyOnOrderCreatedResponseTest Class Doc Comment
 *
 * @category    Class
 * @description DebtorCompanyOnOrderCreatedResponse
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DebtorCompanyOnOrderCreatedResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DebtorCompanyOnOrderCreatedResponse"
     */
    public function testDebtorCompanyOnOrderCreatedResponse()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "address_house_number"
     */
    public function testPropertyAddressHouseNumber()
    {
    }

    /**
     * Test attribute "address_street"
     */
    public function testPropertyAddressStreet()
    {
    }

    /**
     * Test attribute "address_addition"
     */
    public function testPropertyAddressAddition()
    {
    }

    /**
     * Test attribute "address_city"
     */
    public function testPropertyAddressCity()
    {
    }

    /**
     * Test attribute "address_postal_code"
     */
    public function testPropertyAddressPostalCode()
    {
    }

    /**
     * Test attribute "address_country"
     */
    public function testPropertyAddressCountry()
    {
    }
}
