<?php
/**
 * OrderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billie Paella
 *
 * API Specification for Paella API
 *
 * OpenAPI spec version: 1.0
 * Contact: engineering@billie.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for merchantPayment
     *
     * Merchant payment confirmation.
     *
     */
    public function testMerchantPayment()
    {
    }

    /**
     * Test case for orderFullCancellation
     *
     * Order full cancellation.
     *
     */
    public function testOrderFullCancellation()
    {
    }

    /**
     * Test case for orderPost
     *
     * Create new order.
     *
     */
    public function testOrderPost()
    {
    }

    /**
     * Test case for orderShip
     *
     * Ship order.
     *
     */
    public function testOrderShip()
    {
    }

    /**
     * Test case for patchOrder
     *
     * Update order amount / duration.
     *
     */
    public function testPatchOrder()
    {
    }

    /**
     * Test case for retrieveOrder
     *
     * Retrieve order.
     *
     */
    public function testRetrieveOrder()
    {
    }
}
